config/routes.rb
Rails.application.routes.draw do
   devise_for :users,controllers: {sessions: 'sessions'}

   authenticated :user do
     match 'users/list_of_users'=> 'users#list_of_users',via: [:get]
     resources :users
    root to: "users#index", as: :authenticated_root
    resources :groupmessages
  end
  unauthenticated   do
      root to:'welcome#index', as: :unauthenticated_root
      resources :users
  end
resources :users do
      member do
        post :toggle
      end
    end
   resources :conversations do
     resources :messages
   end

end

app/models/groupmessage.rb
class Groupmessage < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :text
end

app/controllers/groupmessages_controller.rb
class GroupmessagesController < ApplicationController
  before_action :set_groupmessage, only: [:show, :edit, :update, :destroy]

  # GET /groupmessages
  # GET /groupmessages.json
  def index
    #@groupmessages = Groupmessage.all
    @groupmessage  = Groupmessage.new
  end

  # GET /groupmessages/1
  # GET /groupmessages/1.json
  def show
  end

  # GET /groupmessages/new
  def new
    @groupmessage = Groupmessage.new
  end

  # GET /groupmessages/1/edit
  def edit
  end

  # POST /groupmessages
  # POST /groupmessages.json
  def create
    #@groupmessage = Groupmessage.new
    @groupmessage = Groupmessage.create(groupmessage_params)
    respond_to do |format|
      format.js
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_groupmessage
      @groupmessage = Groupmessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def groupmessage_params
      params.require(:groupmessage).permit(:text).merge(user_id:current_user.id)
    end
end

app/helpers/groupmessages_helper.rb
module GroupmessagesHelper
 def self_or_other(text)
    text.user == current_user ? "self" : "other"
  end

end

app/views/groupmessages/_form.html.erb
<%= subscribe_to "/groupmessages/new"  %>
<%= simple_form_for @groupmessage, method: :post, remote: true, input_html: {multipart: true} do |f| %>
<div class="form-group" id = 'message-box' >
			<%= f.input :text, :placeholder => "Type a message", :label => false, :autofocus => true, :class => "form-control" %>
		</div>
<% end %>

app/views/groupmessages/create.js.erb
<% publish_to "/groupmessages/new" do  %>
$('.new_groupmessage')[0].reset();
$('#messages_list').html("<%= j (render :partial => "users/message") %>");
<% end %>

app/views/groupmessages/edit.html.erb
<h1>Editing Groupmessage</h1>

<%= render 'form' %>

<%= link_to 'Show', @groupmessage %> |
<%= link_to 'Back', groupmessages_path %>

app/views/groupmessages/index.html.erb
 <%= render "form", groupmessage:@groupmessage %> 

app/views/groupmessages/new.html.erb
<h1>New Groupmessage</h1>

<%= render 'form' %>

<%= link_to 'Back', groupmessages_path %>

app/views/groupmessages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @groupmessage.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @groupmessage.user %>
</p>

<%= link_to 'Edit', edit_groupmessage_path(@groupmessage) %> |
<%= link_to 'Back', groupmessages_path %>