config/routes.rb
Rails.application.routes.draw do
   devise_for :users,controllers: {sessions: 'sessions'}

   authenticated :user do
     match 'users/list_of_users'=> 'users#list_of_users',via: [:get]
     resources :users
    root to: "users#index", as: :authenticated_root
    resources :groupmessages
  end
  unauthenticated   do
      root to:'welcome#index', as: :unauthenticated_root
      resources :users
  end
resources :users do
      member do
        post :toggle
      end
    end
   resources :conversations do
     resources :messages
   end

end

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Keech Keech</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Keech Chat App", authenticated_root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
          <li>
        <% if current_user.present? && current_user.admin? %>
          <%= link_to "view all users",  users_list_of_users_path %>
        <% end %>
      </li>
        <% if user_signed_in? %>
          <!-- <li>
            <%= link_to 'Group Chat',  groupmessages_path %>
          </li> -->
          <li>
            <%= link_to "Logged in as #{current_user.email}" %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete    %>
          </li>
         <% else %>
            <li>
              <%= link_to "Signin", new_user_session_path %>
            </li>
            
            <li>
              <%= link_to "Signup", new_user_path %>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>

  <title>Keech Keech</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>

<body>
  <%= render 'layouts/nav' %>
  <div class="container">
    <div class = "row">
      <div class=" col-sm-4 col-md-2">
        <% if current_user.present? %>
      <div class  = "onlineusers">
          <%= render partial: 'users/onlineuser' %>
        </div>
    </div>
    <% end  %>
      <div class= "col-sm-8 col-md-10">
        <% if alert %>
        <div class="alert alert-danger" role="alert"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><%= notice %><%= alert %></div>
        <% end %>
        <% if notice %>
        <div class="alert alert-success" role="alert"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><%= notice %>
        </div>
        <% end %>
     <div id = "chatbox_parent">

     </div>
     <%= subscribe_to "/chatroom"  %>
     <script>
       PrivatePub.subscribe("/chatroom", function(data, channel)
        {
       var current_user_id = '#{current_user.try(:id)}';
        if (data.receiver_id == current_user_id)
         {
           chatBox.chatWith(data.conversation_id);
          }
          else {
            chatBox.chatWith(data.conversation_id);
          }
         });
       </script>
      <%= yield %>
       </div>
    </div>
  </div>

  <!-- <audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio> -->
</body>

</html>